<?php

namespace AppBundle\Repository;

/**
 * ContentWarningRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContentWarningRepository extends \Doctrine\ORM\EntityRepository
{
}
