<?php

namespace AppBundle\Repository;

/**
 * StripRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StripRepository extends \Doctrine\ORM\EntityRepository
{
}
